# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/iruiz/Downloads/CIM31-012_PFA/CIM31-012_PFA/CIM31-012_PFA.runs/synth_1/Top_FPGA.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param general.usePosixSpawnForFork 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/iruiz/Downloads/CIM31-012_PFA/CIM31-012_PFA/CIM31-012_PFA.cache/wt [current_project]
set_property parent.project_path C:/Users/iruiz/Downloads/CIM31-012_PFA/CIM31-012_PFA/CIM31-012_PFA.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/iruiz/Downloads/CIM31-012_PFA/CIM31-012_PFA/CIM31-012_PFA.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_vhdl -library xil_defaultlib {
  C:/Users/iruiz/Downloads/CIM31-012_PFA/CIM31-012_PFA/CIM31-012_PFA.srcs/sources_1/new/Arith_Unit.vhd
  C:/Users/iruiz/Downloads/CIM31-012_PFA/CIM31-012_PFA/CIM31-012_PFA.srcs/sources_1/new/Logic_Unit.vhd
  C:/Users/iruiz/Downloads/CIM31-012_PFA/CIM31-012_PFA/CIM31-012_PFA.srcs/sources_1/new/Shift_Unit.vhd
  C:/Users/iruiz/Downloads/CIM31-012_PFA/CIM31-012_PFA/CIM31-012_PFA.srcs/sources_1/new/Comp_Unit.vhd
  C:/Users/iruiz/Downloads/CIM31-012_PFA/CIM31-012_PFA/CIM31-012_PFA.srcs/sources_1/new/ALU32.vhd
  C:/Users/iruiz/Downloads/CIM31-012_PFA/CIM31-012_PFA/CIM31-012_PFA.srcs/sources_1/imports/new/AuxRAM.vhd
  C:/Users/iruiz/Downloads/CIM31-012_PFA/CIM31-012_PFA/CIM31-012_PFA.srcs/sources_1/new/AuxReg.vhd
  C:/Users/iruiz/Downloads/CIM31-012_PFA/CIM31-012_PFA/CIM31-012_PFA.srcs/sources_1/imports/user2/Music/PHR_012_PFAUART.xpr/PHR_012_PFA/PHR_012_PFA.srcs/sources_1/new/BOOTLOADER.vhd
  C:/Users/iruiz/Downloads/CIM31-012_PFA/CIM31-012_PFA/CIM31-012_PFA.srcs/sources_1/new/Decoder4_16.vhd
  C:/Users/iruiz/Downloads/CIM31-012_PFA/CIM31-012_PFA/CIM31-012_PFA.srcs/sources_1/new/FF_D.vhd
  C:/Users/iruiz/Downloads/CIM31-012_PFA/CIM31-012_PFA/CIM31-012_PFA.srcs/sources_1/new/R32.vhd
  C:/Users/iruiz/Downloads/CIM31-012_PFA/CIM31-012_PFA/CIM31-012_PFA.srcs/sources_1/new/Bank_R32.vhd
  C:/Users/iruiz/Downloads/CIM31-012_PFA/CIM31-012_PFA/CIM31-012_PFA.srcs/sources_1/imports/new/BinToDec.vhd
  C:/Users/iruiz/Downloads/CIM31-012_PFA/CIM31-012_PFA/CIM31-012_PFA.srcs/sources_1/new/Sum1CP.vhd
  C:/Users/iruiz/Downloads/CIM31-012_PFA/CIM31-012_PFA/CIM31-012_PFA.srcs/sources_1/new/SumPCOffset.vhd
  C:/Users/iruiz/Downloads/CIM31-012_PFA/CIM31-012_PFA/CIM31-012_PFA.srcs/sources_1/new/rs1SumOffset.vhd
  C:/Users/iruiz/Downloads/CIM31-012_PFA/CIM31-012_PFA/CIM31-012_PFA.srcs/sources_1/new/MUXn.vhd
  C:/Users/iruiz/Downloads/CIM31-012_PFA/CIM31-012_PFA/CIM31-012_PFA.srcs/sources_1/new/CP.vhd
  C:/Users/iruiz/Downloads/CIM31-012_PFA/CIM31-012_PFA/CIM31-012_PFA.srcs/sources_1/new/Clock.vhd
  C:/Users/iruiz/Downloads/CIM31-012_PFA/CIM31-012_PFA/CIM31-012_PFA.srcs/sources_1/new/ControlUnit.vhd
  C:/Users/iruiz/Downloads/CIM31-012_PFA/CIM31-012_PFA/CIM31-012_PFA.srcs/sources_1/imports/new/DecToDigit.vhd
  C:/Users/iruiz/Downloads/CIM31-012_PFA/CIM31-012_PFA/CIM31-012_PFA.srcs/sources_1/new/ImmGen.vhd
  C:/Users/iruiz/Downloads/CIM31-012_PFA/CIM31-012_PFA/CIM31-012_PFA.srcs/sources_1/new/LoadStoreUnit.vhd
  C:/Users/iruiz/Downloads/CIM31-012_PFA/CIM31-012_PFA/CIM31-012_PFA.srcs/sources_1/new/MUX4_Reg.vhd
  C:/Users/iruiz/Downloads/CIM31-012_PFA/CIM31-012_PFA/CIM31-012_PFA.srcs/sources_1/new/MemData.vhd
  C:/Users/iruiz/Downloads/CIM31-012_PFA/CIM31-012_PFA/CIM31-012_PFA.srcs/sources_1/new/MemInstr.vhd
  C:/Users/iruiz/Downloads/CIM31-012_PFA/CIM31-012_PFA/CIM31-012_PFA.srcs/sources_1/new/PreDecode.vhd
  C:/Users/iruiz/Downloads/CIM31-012_PFA/CIM31-012_PFA/CIM31-012_PFA.srcs/sources_1/new/Procesador_RV32E.vhd
  C:/Users/iruiz/Downloads/CIM31-012_PFA/CIM31-012_PFA/CIM31-012_PFA.srcs/sources_1/imports/new/ROM_Letter.vhd
  C:/Users/iruiz/Downloads/CIM31-012_PFA/CIM31-012_PFA/CIM31-012_PFA.srcs/sources_1/imports/new/TextRAM.vhd
  C:/Users/iruiz/Downloads/CIM31-012_PFA/CIM31-012_PFA/CIM31-012_PFA.srcs/sources_1/imports/new/vga_control.vhd
  C:/Users/iruiz/Downloads/CIM31-012_PFA/CIM31-012_PFA/CIM31-012_PFA.srcs/sources_1/imports/new/VGA.vhd
  C:/Users/iruiz/Downloads/CIM31-012_PFA/CIM31-012_PFA/CIM31-012_PFA.srcs/sources_1/imports/user2/Music/PHR_012_PFAUART.xpr/PHR_012_PFA/PHR_012_PFA.srcs/sources_1/new/UART_RX.vhd
  C:/Users/iruiz/Downloads/CIM31-012_PFA/CIM31-012_PFA/CIM31-012_PFA.srcs/sources_1/new/TOP_FPGA.vhd
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/iruiz/Downloads/CIM31-012_PFA/CIM31-012_PFA/CIM31-012_PFA.srcs/constrs_1/imports/Downloads/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/iruiz/Downloads/CIM31-012_PFA/CIM31-012_PFA/CIM31-012_PFA.srcs/constrs_1/imports/Downloads/Basys3_Master.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Users/iruiz/Downloads/CIM31-012_PFA/CIM31-012_PFA/CIM31-012_PFA.srcs/utils_1/imports/synth_1/testImmGen.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top Top_FPGA -part xc7a35tcpg236-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top_FPGA.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file Top_FPGA_utilization_synth.rpt -pb Top_FPGA_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
