@echo off
REM ****************************************************************************
REM Vivado (TM) v2025.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu May 14 13:11:50 +0200 2026
REM SW Build 6299465 on Fri Nov 14 19:35:11 GMT 2025
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
set SIM_VER_XSIM=
set GCC_VER_XSIM=9.3.0
REM simulate design
echo "xsim Test_Procesador_RV32E_behav -key {Behavioral:sim_1:Functional:Test_Procesador_RV32E} -tclbatch Test_Procesador_RV32E.tcl -view C:/Users/user2/Downloads/PHR_012_PFA.xpr/PHR_012_PFA/PHR_012_PFA.srcs/sim_1/imports/PFA_RISCV/Test_Procesador_RV32E_behav.wcfg -log simulate.log"
call xsim  Test_Procesador_RV32E_behav -key {Behavioral:sim_1:Functional:Test_Procesador_RV32E} -tclbatch Test_Procesador_RV32E.tcl -view C:/Users/user2/Downloads/PHR_012_PFA.xpr/PHR_012_PFA/PHR_012_PFA.srcs/sim_1/imports/PFA_RISCV/Test_Procesador_RV32E_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
